version: "3.9"

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - NEWS_TOPIC=${NEWS_TOPIC:-India’s tech policy}
